/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectSubjectIdRouteImport } from './routes/subject.$subjectId'
import { Route as QuizSubjectIdTopicIdRouteImport } from './routes/quiz.$subjectId.$topicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSubjectIdRoute = SubjectSubjectIdRouteImport.update({
  id: '/subject/$subjectId',
  path: '/subject/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSubjectIdTopicIdRoute = QuizSubjectIdTopicIdRouteImport.update({
  id: '/quiz/$subjectId/$topicId',
  path: '/quiz/$subjectId/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRoute
  '/quiz/$subjectId/$topicId': typeof QuizSubjectIdTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRoute
  '/quiz/$subjectId/$topicId': typeof QuizSubjectIdTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRoute
  '/quiz/$subjectId/$topicId': typeof QuizSubjectIdTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/subject/$subjectId' | '/quiz/$subjectId/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/subject/$subjectId' | '/quiz/$subjectId/$topicId'
  id: '__root__' | '/' | '/subject/$subjectId' | '/quiz/$subjectId/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubjectSubjectIdRoute: typeof SubjectSubjectIdRoute
  QuizSubjectIdTopicIdRoute: typeof QuizSubjectIdTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subjectId': {
      id: '/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/subject/$subjectId'
      preLoaderRoute: typeof SubjectSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$subjectId/$topicId': {
      id: '/quiz/$subjectId/$topicId'
      path: '/quiz/$subjectId/$topicId'
      fullPath: '/quiz/$subjectId/$topicId'
      preLoaderRoute: typeof QuizSubjectIdTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubjectSubjectIdRoute: SubjectSubjectIdRoute,
  QuizSubjectIdTopicIdRoute: QuizSubjectIdTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
